# Generated by Django 6.0.2 on 2026-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
